image: docker:latest

services:
  - docker:dind
  
variables:
  BOT_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/bot"
  WEB_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/web"
  
stages:
 - build

before_script:
 - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker-bot:
  stage: build
  script:
    - docker build --pull -t "$BOT_IMAGE_NAME":"$CI_COMMIT_TAG" -f Dockerfile.bot .
    - docker push "$BOT_IMAGE_NAME":"$CI_COMMIT_TAG"
  only:
    - tags

docker-web:
  stage: build
  script:
    - docker build --pull -t "$WEB_IMAGE_NAME":"$CI_COMMIT_TAG" -f Dockerfile.web .
    - docker push "$WEB_IMAGE_NAME":"$CI_COMMIT_TAG"
  only:
    - tags
    
