image: docker:latest

services:
  - docker:dind
  
variables:
  BOT_IMAGE_NAME: "$CI_REGISTRY_IMAGE"/bot
  WEB_IMAGE_NAME: "$CI_REGISTRY_IMAGE"/web
  
stages:
 - build
 - push

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

bot-build:
  stage: build
  script:
    - docker build --pull -t "$BOT_IMAGE_NAME":"$CI_COMMIT_TAG" -f Dockerfile.bot .
  only:
    - tags

bot-push:
  stage: push
  script:
    - docker push "$BOT_IMAGE_NAME":"$CI_COMMIT_TAG"
  only:
    - tags

web-build:
  stage: build
  script:
    - docker build --pull -t "$WEB_IMAGE_NAME":"$CI_COMMIT_TAG" -f Dockerfile.web .
  only:
    - tags


web-push:
  stage: push
  script:
    - docker push "$WEB_IMAGE_NAME":"$CI_COMMIT_TAG"
  only:
    - tags
    
