version: "3"
services:
  bot:
    image: shywim/airhornbot-bot:latest
    volumes:
      - data:/data
      - ./config:/etc/airhornbot
      - .t/plugins:/etc/airhornbot/plugins
    networks:
      - back
    links:
      - db
  web:
    image: shywim/airhornbot-web:latest
    volumes:
      - data:/data
      - ./config:/etc/airhornbot
    networks:
      - front
      - back
    ports:
      - 14000:14000
    links:
      - db
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - back
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airhorn
      POSTGRES_PASSWORD:
      POSTGRES_DB: airhorn
    networks:
      - back
networks:
  back:
  front:
volumes:
  data:
  db-data:
  redis-data:

