FROM golang:1.9.2-alpine3.6

VOLUME ["/config", "/data"]

WORKDIR /go/src/github.com/Shywim/airhornbot
COPY . .

RUN apk add --no-cache git
RUN go get -u -d github.com/magefile/mage \
	&& cd $GOPATH/src/github.com/magefile/mage \
	&& go run bootstrap.go

RUN mage AirhornWeb

RUN ln -s $GOPATH/src/github.com/Shywim/airhornbot/config /config
RUN ln -s $GOPATH/src/github.com/Shywim/airhornbot/data /data

CMD ["airhornweb"]

