FROM golang:1.9.2-alpine3.6

VOLUME ["/etc/airhornbot", "/data", "/etc/airhornbot/plugins"]

WORKDIR /go/src/github.com/Shywim/airhornbot
COPY . .

# go plugin package requires CGO
RUN apk add --no-cache git gcc musl-dev ffmpeg
RUN go get -u -d github.com/magefile/mage \
	&& cd $GOPATH/src/github.com/magefile/mage \
	&& go run bootstrap.go

RUN mage AirhornBot

CMD ["/go/src/github.com/Shywim/airhornbot/airhornbot"]

