FROM golang:1.13.4-alpine3.10

VOLUME ["/etc/airhornbot", "/data"]

WORKDIR /go/src/gitlab.com/Shywim/airhornbot
COPY . .

RUN apk add --no-cache git ffmpeg
RUN go get -u -d github.com/magefile/mage \
	&& cd $GOPATH/src/github.com/magefile/mage \
	&& go run bootstrap.go

RUN mage AirhornWeb

CMD ["/go/src/gitlab.com/Shywim/airhornbot/airhornweb"]

