FROM golang:1.9.2-alpine3.6

VOLUME ["/etc/airhornbot", "/data"]

WORKDIR /go/src/github.com/Shywim/airhornbot
COPY . .

RUN apk add --no-cache git
RUN go get -u -d github.com/magefile/mage \
	&& cd $GOPATH/src/github.com/magefile/mage \
	&& go run bootstrap.go

RUN mage AirhornWeb

CMD ["airhornweb"]

